let languages = {
  en : {
    // Html text
    pageTitle: "Mandala Playground",
    fillLabel: "Figure",
    strokeLabel: "Stroke",
    radiusLabel: "Radius",
    distanceLabel: "Distance",
    angleLabel: "Angle",
    footerLabel: "Made with joy by Natalia Vera",
    languageLabel: "Language",
    englishLabel: "English",
    spanishLabel: "Spanish",
    chineseLabel: "Chinese",
    // Tooltips
    upTitle:"Move forward",
    downTitle: "Move backward",
    fillTitle: "Color inside the figure",
    strokeColorTitle: "Color of the stroke",
    strokeWidthTitle: "Width of the stroke",
    quantityTitle: "Number of figures",
    figureTitle: "Figure",
    triangleTitle: "Triangle",
    circleTitle: "Circle",
    lineTitle: "Line",
    squareTitle: "Square",
    visibilityTitle: "Show/hide this layer",
    removeTitle: "Remove this layer",
    radiusTitle: "Figure size",
    distanceTitle:"Distance from mandala's center to figures's center",
    addLayerTitle:"Add a new layer",
    //
    backgroundTitle: "Mandala background color",
    undoTitle: "Undo change",
    redoTitle: "Redo change",
    downloadTitle: "Download as image",
    resetTitle: "Remove all layers",
  },
  es: {
    // Html text
    pageTitle: "Juega con Mandalas",
    fillLabel: "Figura",
    strokeLabel: "Borde",
    radiusLabel: "Tamaño",
    distanceLabel: "Distancia",
    angleLabel: "Ángulo",
    footerLabel: "Hecho con cariño por Natalia Vera",
    languageLabel: "Idioma",
    englishLabel: "Ingles",
    spanishLabel: "Español",
    chineseLabel: "Chino",
    // Tooltips
    upTitle:"Mover capa hacia atrás (menor visibilidad)",
    downTitle: "Mover capa hacia el frente (mayor visibilidad)",
    fillTitle: "Color de relleno de la figura",
    strokeColorTitle: "Color del borde",
    strokeWidthTitle: "Ancho del borde",
    quantityTitle: "Cantidad de figuras",
    figureTitle: "Tipo de figura",
    triangleTitle: "Triángulo",
    circleTitle: "Círculo",
    lineTitle: "Línea",
    squareTitle: "Cuadrado",
    visibilityTitle: "Mostrar/ocultar esta capa",
    removeTitle: "Eliminar esta capa",
    radiusTitle: "Tamaño de las figuras de esta capa",
    distanceTitle:"Distancia desde el centro del mandala hasta las figuras",
    addLayerTitle:"Añadir una nueva capa",
    //
    backgroundTitle: "Color de fondo del mandala",
    undoTitle: "Deshacer cambio",
    redoTitle: "Rehacer cambio",
    downloadTitle: "Descargar como imagen",
    resetTitle: "Eliminar todas las capas",
  },
  zh: {
    // Html text
    pageTitle: "曼陀罗游乐场",
    fillLabel: "填充",
    strokeLabel: "边框",
    radiusLabel: "半径",
    distanceLabel: "距离",
    angleLabel: "Angle",
    footerLabel: "由 Natalia Vera 精心制作",
    languageLabel: "语言",
    englishLabel: "英语",
    spanishLabel: "西班牙语",
    chineseLabel: "中文",
    // Tooltips
    upTitle:"向上移动",
    downTitle: "向下移动",
    fillTitle: "图形内的颜色",
    strokeColorTitle: "Color of the stroke",
    strokeWidthTitle: "Width of the stroke",
    quantityTitle: "图形数量",
    figureTitle: "图形",
    triangleTitle: "三角形",
    circleTitle: "圆形",
    lineTitle: "直线",
    squareTitle: "正方形",
    visibilityTitle: "显示/隐藏此图层",
    removeTitle: "删除此层",
    radiusTitle: "图形大小",
    distanceTitle:"从曼陀罗中心到图形中心的距离",
    addLayerTitle:"添加新图层",
    //    
    backgroundTitle: "曼陀罗背景颜色",
    undoTitle: "撤消更改",
    redoTitle: "重做更改",
    downloadTitle: "下载为图像",
    resetTitle: "删除所有图层",
  }
}