let languages = {
  en : {
    // Html text
    pageTitle: "Mandala Playground",
    fillLabel: "Fill",
    borderLabel: "Border",
    quantityLabel: "Quantity",
    radiusLabel: "Radius",
    distanceLabel: "Distance",
    footerLabel: "Made with joy by Natalia Vera",
    languageLabel: "Language",
    englishLabel: "English",
    spanishLabel: "Spanish",
    chineseLabel: "Chinese",
    // Tooltips
    upTitle:"move up",
    downTitle: "move down",
    fillTitle: "Color inside the figure",
    borderTitle: "Border of the color",
    quantityTitle: "number of figures",
    figureTitle: "figura",
    triangleTitle: "triangle",
    circleTitle: "circle",
    lineTitle: "line",
    squareTitle: "square",
    visibilityTitle: "Show/hide this layer",
    removeTitle: "Remove Layer",
    radiusTitle: "Figure Size",
    distanceTitle:"Distance from mandala's center to figures's center"
  },
  es: {
    pageTitle: "Juega con Mandalas",
    fillLabel: "Relleno",
    borderLabel: "Borde",
    quantityLabel: "Cantidad",
    radiusLabel: "Tamaño",
    distanceLabel: "Distancia",
    footerLabel: "Hecho con cariño por Natalia Vera",
    languageLabel: "Idioma",
    englishLabel: "Ingles",
    spanishLabel: "Español",
    chineseLabel: "Chino",
    // Tooltips
    upTitle:"Mover capa hacia atrás",
    downTitle: "Mover capa hacia adelante",
    fillTitle: "Color de relleno de la figura",
    borderTitle: "Border of the color",
    quantityTitle: "Cantidad de figuras",
    figureTitle: "Figura",
    triangleTitle: "Triángulo",
    circleTitle: "Círculo",
    lineTitle: "Linea",
    squareTitle: "Cuadrado",
    visibilityTitle: "Mostrar-Ocultar esta capa",
    removeTitle: "Borrar capa",
    radiusTitle: "Tamaño de las figuras",
    distanceTitle:"Distancia desde el centro hasta el centro de las figuras"
  },
  zh: {
    pageTitle: "Mandala Playground",
    fillLabel: "Fill",
    borderLabel: "Border",
    quantityLabel: "Quantity",
    radiusLabel: "Radius",
    distanceLabel: "Distance",
    footerLabel: "Made with joy by Natalia Vera",
    languageLabel: "Language",
    englishLabel: "English",
    spanishLabel: "Spanish",
    chineseLabel: "Chinese",
    // Tooltips
    upTitle:"move up",
    downTitle: "move down",
    fillTitle: "Color inside the figure",
    borderTitle: "Border of the color",
    quantityTitle: "number of figures",
    figureTitle: "figura",
    triangleTitle: "triangle",
    circleTitle: "circle",
    lineTitle: "line",
    squareTitle: "square",
    visibilityTitle: "Show/hide this layer",
    removeTitle: "Remove Layer",
    radiusTitle: "Figure Size",
    distanceTitle:"Distance from mandala's center to figure's center"
  }
}